In [1]:
print("Hi Jupyter Notebook")

Hi Jupyter Notebook


In [1]:
#Numpy learning 

In [55]:
import numpy as np #Numpy importing

In [8]:
##creating numpy array(s)

In [9]:
list1 = [1,2,3,4,5,6]

In [10]:
list1

[1, 2, 3, 4, 5, 6]

In [11]:
NArray1 = np.array(list1)

In [12]:
NArray1

array([1, 2, 3, 4, 5, 6])

In [13]:
type(NArray1)

numpy.ndarray

In [14]:
##multi D Array

In [15]:
Narray2 = np.array([[1,2,3],[4,5,6]])

In [16]:
print(Narray2)

[[1 2 3]
 [4 5 6]]


In [17]:
#zero matrix with row and columns

In [18]:
NPZeroMatrix = np.zeros((2,3))

In [19]:
print(NPZeroMatrix)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
type(NPZeroMatrix)

numpy.ndarray

In [21]:
n1=np.zeros((10,10))

In [22]:
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
#If we have to get some other number insted of zero then we will use full method

In [24]:
n2=np.full((2,3),5)

In [25]:
n2

array([[5, 5, 5],
       [5, 5, 5]])

In [26]:
#initalizing a NumPy array within a range---------------ARANGE

In [27]:
n3=np.arange(10,20)   #10 to 19

In [28]:
n3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
#in case if we need a specfic gap between these numbers in array then

In [30]:
n4=np.arange(10,20,2)  #gap of 2 #last number will be exclusive

In [31]:
n4

array([10, 12, 14, 16, 18])

In [32]:
#random module

In [33]:
n5 = np.random.randint(1,100,5) #any 5 rendom number between 1 to 100

In [34]:
n5

array([54, 35, 66, 91, 59])

In [35]:
#checking the shape of a numpy array

In [38]:
n6 = np.array([[1,2,3],[4,5,6]]) #2 rows 3 coloumns   #list of list 

In [39]:
np.shape(n6)

(2, 3)

In [42]:
n6.shape = (6,1)  #we can change the shape of array as well

In [43]:
n6

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [44]:
#Stacking two numpy array : horizontal,vertical, column stack

In [50]:
n1=np.array([1,2,3])
n2=np.array([7,8,9])

In [52]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [7, 8, 9]])

In [53]:
np.hstack((n1,n2))

array([1, 2, 3, 7, 8, 9])

In [54]:
np.column_stack((n1,n2))

array([[1, 7],
       [2, 8],
       [3, 9]])

In [56]:
#interscation and diffrence in numpy

In [57]:
n1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [58]:
n2 = np.array([9,10,11,12,13,14,15,16,17])

In [59]:
np.intersect1d(n1,n2)   #intersection or common

array([ 9, 10])

In [61]:
np.setdiff1d(n1,n2)   #what is in n1 which is not in n2

array([1, 2, 3, 4, 5, 6, 7, 8])